### ISSUE TITLE
Feature: S3 Support

### ISSUE THREAD

**Issue by kgnfth** [PleasureTools/joyBox#34]
it would be great if it had S3 support for saving the files instead in local folder, because folder gets huge in no time

also i have build and pushed a docker image here https://github.com/joyboxxx/joybox/pkgs/container/joybox
it will run on every new commit, but i can change it to build on every new release tag if u guys agree ??

**Comment by weigeloveu** [comment]
when i try to build it,there are lots of npm error,have you met it?

**Comment by kgnfth** [comment]
> when i try to build it,there are lots of npm error,have you met it?

No, you can get it from here https://github.com/joyboxxx/joybox/pkgs/container/joybox

**Comment by ReneSch** [comment]
> 

Thanks for the work! do you got a howto use it? When i run the docker pull command i cant start the image 
`docker run --name joybox --rm -d -p 8080:80 -p 8081:443 -v $(pwd):/app/data joybox
Unable to find image 'joybox:latest' locally
docker: Error response from daemon: pull access denied for joybox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`

running with the image id:
`docker run -t c4324a07438d --rm -d -p 8080:80 -p 8081:443 -v $(pwd):/app/data joybox
npm info using npm@7.19.1
npm info using node@v16.5.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/app/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/root/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 8ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 17ms
npm timing npm:load:configload Completed in 17ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 2ms
npm timing npm:load:cleanupLog Completed in 3ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 30ms
7.19.1
npm timing npm Completed in 585ms
npm info ok
` but then the image is stopping.

soo.. whats the command i need to use in order to run your package?
